"""empty message

Revision ID: 7bcdb59447a5
Revises: b034e60a0dfc
Create Date: 2023-05-06 20:24:46.625491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcdb59447a5'
down_revision = 'b034e60a0dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gexing', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('desc', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('email')
        batch_op.drop_column('gender')
        batch_op.drop_column('desc')
        batch_op.drop_column('gexing')

    # ### end Alembic commands ###
